openapi: 3.0.3
info:
  title: Pizza Store API
  version: 1.0.0
  description: >
    Sample CRUD-style API (9 endpoints) for testing Swagger UI.
    Use this file with the OpenAPI Swagger Viewer.
servers:
  - url: https://api.pizzastore.example.com
tags:
  - name: Pizzas
    description: Manage pizzas
  - name: Orders
    description: Manage orders

paths:
  /pizzas:
    get:
      tags: [Pizzas]
      summary: List pizzas
      operationId: listPizzas
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pizza'
                  total:
                    type: integer
                    example: 42
    post:
      tags: [Pizzas]
      summary: Create pizza
      operationId: createPizza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaInput'
      responses:
        '201':
          description: Pizza created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '400':
          $ref: '#/components/responses/BadRequest'

  /pizzas/{pizzaId}:
    get:
      tags: [Pizzas]
      summary: Get pizza by id
      operationId: getPizza
      parameters:
        - $ref: '#/components/parameters/PizzaId'
      responses:
        '200':
          description: Pizza details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [Pizzas]
      summary: Update pizza
      operationId: updatePizza
      parameters:
        - $ref: '#/components/parameters/PizzaId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaInput'
      responses:
        '200':
          description: Pizza updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Pizzas]
      summary: Delete pizza
      operationId: deletePizza
      parameters:
        - $ref: '#/components/parameters/PizzaId'
      responses:
        '204':
          description: Deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /orders:
    get:
      tags: [Orders]
      summary: List orders
      operationId: listOrders
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [CREATED, PREPARING, OUT_FOR_DELIVERY, DELIVERED, CANCELLED]
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  total:
                    type: integer
                    example: 15
    post:
      tags: [Orders]
      summary: Create order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'

  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get order by id
      operationId: getOrder
      parameters:
        - $ref: '#/components/parameters/OrderId'
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [Orders]
      summary: Cancel order
      operationId: cancelOrder
      parameters:
        - $ref: '#/components/parameters/OrderId'
      responses:
        '200':
          description: Order cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    Offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    PizzaId:
      name: pizzaId
      in: path
      required: true
      schema:
        type: string
      description: Pizza identifier
    OrderId:
      name: orderId
      in: path
      required: true
      schema:
        type: string
      description: Order identifier

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: BAD_REQUEST
            message: Invalid request payload
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: NOT_FOUND
            message: Resource not found

  schemas:
    Pizza:
      type: object
      required: [id, name, size, price, isVeg]
      properties:
        id:
          type: string
          example: pz_101
        name:
          type: string
          example: Margherita
        size:
          type: string
          enum: [S, M, L]
          example: M
        price:
          type: number
          format: float
          example: 249.0
        isVeg:
          type: boolean
          example: true
        toppings:
          type: array
          items:
            type: string
          example: [cheese, basil]
        createdAt:
          type: string
          format: date-time
          example: '2026-02-09T10:30:00Z'

    PizzaInput:
      type: object
      required: [name, size, price, isVeg]
      properties:
        name:
          type: string
          example: Farmhouse
        size:
          type: string
          enum: [S, M, L]
          example: L
        price:
          type: number
          format: float
          example: 399.0
        isVeg:
          type: boolean
          example: true
        toppings:
          type: array
          items:
            type: string
          example: [onion, capsicum, tomato]

    Order:
      type: object
      required: [id, status, items, totalAmount]
      properties:
        id:
          type: string
          example: od_9001
        status:
          type: string
          enum: [CREATED, PREPARING, OUT_FOR_DELIVERY, DELIVERED, CANCELLED]
          example: CREATED
        items:
          type: array
          items:
            type: object
            required: [pizzaId, qty]
            properties:
              pizzaId:
                type: string
                example: pz_101
              qty:
                type: integer
                minimum: 1
                example: 2
        notes:
          type: string
          example: Extra oregano please
        totalAmount:
          type: number
          format: float
          example: 498.0
        createdAt:
          type: string
          format: date-time
          example: '2026-02-09T10:45:00Z'

    OrderInput:
      type: object
      required: [items]
      properties:
        items:
          type: array
          minItems: 1
          items:
            type: object
            required: [pizzaId, qty]
            properties:
              pizzaId:
                type: string
              qty:
                type: integer
                minimum: 1
        notes:
          type: string

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: BAD_REQUEST
        message:
          type: string
          example: Something went wrong
